version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    depends_on:
      - webserver
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    ports:
      - "5173:5173"
    volumes:
      # - ./:/var/www
      - ./storage:/var/www/storage
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  webserver:
    platform: linux/x86_64
    image: nginx:alpine
    container_name: webserver
    restart: always
    tty: true
    ports:
      - "8989:80"
    volumes:
    # - ./:/var/www
      - ./public:/var/www/public # Mounting only the public folder
      - ./storage:/var/www/storage
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - app-network


  db:
    image: postgres:latest
    container_name: db
    restart: always
    tty: true
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local